name: Update packages

on:
  repository_dispatch:
  release:
    types: published
  push:
    branches:
      - main
  schedule:
    - cron: 0 */12 * * *
  watch:
    types: started

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id
        
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install git subversion git-core wget
        sudo timedatectl set-timezone "$TZ"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        
    - name: Clone packages
      run: |
        cd $GITHUB_WORKSPACE
        chmod +x packages.sh
        git clone https://github.com/canmeng99/openwrt-package.git
        cd openwrt-package
        rm -Rf *
        git rm --cache *
        $GITHUB_WORKSPACE/packages.sh
    - name: Upload
      env: 
        ACCESS_TOKEN: ${{ secrets.PAT }}
      run: |
        [ -e $GITHUB_WORKSPACE/LICENSE ] && cp $GITHUB_WORKSPACE/LICENSE $GITHUB_WORKSPACE/openwrt-package
        [ -e $GITHUB_WORKSPACE/README.md ] && cp $GITHUB_WORKSPACE/README.md $GITHUB_WORKSPACE/openwrt-package
        cd $GITHUB_WORKSPACE/openwrt-package
        git add .
        git commit -m "update$(TZ='Asia/Shanghai' date +-%m.%d)"
        git push --quiet "https://${{ secrets.PAT }}@github.com/canmeng99/openwrt-package.git" HEAD:packages
